### ISSUE TITLE
CMake does not correctly find a dir  for libswipl.so in some systems

### ISSUE THREAD

**Issue by gmarpons** [gmarpons/Crisp#10]
E.g.: in Linux Mint Debian Edition.

**Comment by gmarpons** [comment]
commit 14b01ab46beb4f6d0d2f14282eafb6ac2ab639ae fixes this for LMDE when compiling in Release mode (in Debug mode it fails because of #16).

**Comment by rizsotto** [comment]
So, this issue is solved. Debug mode problem has separate ticket.
